In [1]:
import sys
import django
import os
file_dir = "/Users/mirbilal/Desktop/MobCommission/commissionV2/"
if file_dir not in sys.path:
    sys.path.insert(0, file_dir)

os.environ["DJANGO_SETTINGS_MODULE"] = "commissionerv2.settings"
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
django.setup()
from os import path, environ
from datetime import datetime
from services.zayev.environment.market_simulator import MarketSimulator
from services.zayev.service_layer.forester import Forester
import tensorflow as tf
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.metrics import accuracy_score


2023-12-09 21:08:14.235128: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:


starting_time_step = datetime(year=1995, month=1, day=1, hour=10)

db_params = {
    'database': environ.get("POSTGRES_DB"),
    'user': environ.get("POSTGRES_USER"),
    'password': environ.get("POSTGRES_PASSWORD"),
    'host': environ.get("DB_HOST"),
    'port': environ.get("DB_PORT"),
}
env_config = {
    "db_params": db_params, 
    "max_episode_steps": 1000, 
    "the_current_time_step": starting_time_step,
    "print_output": False,
    "is_test": False,
    "test_steps": 200,
    "n_step_stocks": 5,
    "n_step_cmmdties": 5,
    "preparing": True
} 

market = MarketSimulator(env_config=env_config)

In [3]:
market.reset()

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [4]:
forest = Forester(market=market)
print("done")

done


In [5]:
forest.make_forest_data()

In [9]:
X_train = forest.train_input
y_train = forest.train_output
y_test = forest.test_output
X_test = forest.test_input

print(X_train[9])
# print(X_test)
print(y_train[8])
# print(y_test)

[ 1.49639915e-02 -8.50818621e-03 -4.48764145e-03  2.28122451e-03
  2.35183485e-02  3.03715492e-03  1.29796454e-02  5.22536868e-03
  3.13730489e-03 -6.75404387e-04 -3.50180951e-02 -3.15110921e-02
 -2.26922180e-02 -3.89107075e-02 -3.98692603e-03  1.02915384e-03
  1.88470028e-02  1.12386743e-02  2.77893229e-02  6.73462503e-03
 -2.22613055e-03 -1.12463872e-02 -3.73182763e-03  4.14643446e-03
  5.16252945e-03  3.78137953e-02  4.10717068e-02  3.57146809e-02
  5.57466733e-02  4.16309734e-02  1.94529730e-03  9.68548209e-03
  3.62461991e-03 -3.07445644e-03 -1.41437252e-02  1.78049749e-02
  3.67290709e-02  1.89020626e-02  2.97636466e-02  1.51442092e-03
  2.33995592e-02  3.32378741e-02  3.04598742e-02  3.89001026e-02
  2.79919740e-02  7.97810541e-03 -1.65280503e-02 -1.49548909e-02
 -1.08078437e-02 -5.59201052e-03  3.48037217e-04  1.61778604e-03
  1.51521489e-03  6.63276318e-03  8.50068392e-03  2.10359897e-05
  4.62129242e-03  1.84297344e-03  1.54455347e-03  1.42750937e-03
  9.86964536e-04  7.88353

In [10]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [14]:
X_test = forest.test_input
# X_test = forest.train_input
y_pred = rf.predict(X_test)

In [16]:
print(y_pred[:, 0])

[10. 12. 10. 11. 10. 10. 11. 13. 11. 10. 10. 11. 11. 12. 12. 12. 11. 10.
 11. 10.  9.  9.  8. 10. 11. 11. 11.  9.  9.  9.  9. 11. 10. 11. 11. 11.
 10. 10.  7.  7.  9. 11. 10. 11. 10. 10. 11. 11. 11. 10. 11.  7.  6. 10.
  9.  9.  9. 12. 11. 13. 10. 10. 11. 11. 10. 12. 10.  9. 11.  9. 12. 10.
 12. 10. 10.  7.  7.  9.  6. 21. 11. 10. 10. 11. 10.  9. 11. 10. 11.  7.
  9.  9. 21. 11. 12.  7. 11. 10. 11. 11. 11. 11.  9.  9.  8.  9.  8.  9.
 11. 11. 11. 10.  9. 11. 11. 10. 10. 11. 10. 10. 11. 11. 11. 11. 11. 10.
 10. 11. 10. 11. 11.  9. 10. 11. 11. 11. 11. 10. 10. 11. 10. 10. 11.  9.
 10. 10. 10.  9. 10. 10. 11. 11. 11. 10. 10. 11. 10. 11. 11.  9.  9. 11.
 10. 10. 10.  9.  9. 10. 10. 10.  9.  9. 10. 11.  8. 10. 11. 10. 10. 10.
 10. 10. 10. 10. 10.  9. 10. 10. 10. 10. 10. 12. 11. 12. 11. 10. 11. 10.
  9. 10.  7.  8.  7.  8. 11.  8.  8.  8.  8. 10.  8. 11. 10.]


In [18]:
y_test = forest.test_output
# y_test = forest.train_output
y_test_first_column = [row[0] for row in y_test]
y_pred_first_column = [row[0] for row in y_pred]

In [19]:
y_test = forest.test_output
accuracy = accuracy_score(y_test_first_column, y_pred_first_column)
print("Accuracy:", accuracy)

Accuracy: 0.215962441314554


In [ ]:
forest.market.state

In [20]:

from matplotlib.dates import relativedelta


nw_starting_time_step = datetime(year=1995, month=1, day=1, hour=10) + relativedelta(hours=1000)

nw_db_params = {
    'database': environ.get("POSTGRES_DB"),
    'user': environ.get("POSTGRES_USER"),
    'password': environ.get("POSTGRES_PASSWORD"),
    'host': environ.get("DB_HOST"),
    'port': environ.get("DB_PORT"),
}
nw_env_config = {
    "db_params": nw_db_params, 
    "max_episode_steps": 200, 
    "the_current_time_step": nw_starting_time_step,
    "print_output": False,
    "is_test": False,
    "test_steps": 200,
    "n_step_stocks": 5,
    "n_step_cmmdties": 5,
    "preparing": True
} 

nw_market = MarketSimulator(env_config=nw_env_config)
nw_market.reset()
nw_forest = Forester(market=nw_market)

In [21]:
nw_forest.make_forest_data()

In [22]:
nw_X_train = nw_forest.train_input
nw_y_train = nw_forest.train_output
nw_y_test = nw_forest.test_output
nw_X_test = nw_forest.test_input

nw_X_test = nw_forest.test_input
nw_y_pred = rf.predict(nw_X_test)

nw_y_test = nw_forest.test_output
nw_y_test_first_column = [row[1] for row in nw_y_test]
nw_y_pred_first_column = [row[1] for row in nw_y_pred]

In [23]:
accuracy = accuracy_score(nw_y_test_first_column, nw_y_pred_first_column)
print("Accuracy:", accuracy)

Accuracy: 0.9069767441860465


In [32]:
time_data = {}
for it in range(5):
    rand_acts = nw_forest.act_random()
    state, reward, done, info = nw_forest.market.step([rand_acts])
    time_data[nw_forest.market.the_current_time_step] = state
nw_state = state
print(nw_forest.market.the_current_time_step)
flat_state = np.array([nw_forest.get_flattened_states(nw_state)])
my_pred = rf.predict(flat_state)
print(len(nw_y_pred), my_pred)

1995-03-09 14:30:00+00:00
43 [[11. 11. 13. 12. 10.]]
