In [1]:
import sys
import django
import os
file_dir = "/Users/mirbilal/Desktop/MobCommission/commissionV2/"
if file_dir not in sys.path:
    sys.path.insert(0, file_dir)

os.environ["DJANGO_SETTINGS_MODULE"] = "commissionerv2.settings"
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
django.setup()
from datetime import datetime
from os import environ
from services.zayev.service_layer.agent import PPOAgent as ZPPO
from matplotlib.dates import relativedelta
import numpy as np


2023-10-16 10:25:07.311668: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<Figure size 1800x900 with 0 Axes>

In [7]:

starting_time_step = datetime(year=1995, month=1, day=1, hour=10) + relativedelta(hours=0)

db_params = {
            'database': environ.get("POSTGRES_DB"),
            'user': environ.get("POSTGRES_USER"),
            'password': environ.get("POSTGRES_PASSWORD"),
            'host': environ.get("DB_HOST"),
            'port': environ.get("DB_PORT"),
        }
env_config = {
    "db_params": db_params, 
    "max_episode_steps": 5, 
    "the_current_time_step": starting_time_step,
    "print_output": False,
    "test_steps": 10,
    "n_step_stocks": 5,
    "n_step_cmmdties": 5,
    "epsilon": 0.4
} 



zayev = ZPPO(env_config)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/optimizers/legacy/adam.py:118: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [3]:
print(zayev.Actor.Actor.summary())

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 stock_observation_input (I  [(None, 5, 14)]              0         []                            
 nputLayer)                                                                                       
                                                                                                  
 commodity_observation_inpu  [(None, 6, 7)]               0         []                            
 t (InputLayer)                                                                                   
                                                                                                  
 wallet_observation_input (  [(None, 1)]                  0         []                            
 InputLayer)                                                                                  

In [3]:
zayev.save()

2023-10-16 08:57:55.538556: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-10-16 08:57:55.559347: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_5/kernel/Assign' id:216 op device:{requested: '', assigned: ''} def:{{{node dense_5/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_5/kernel, dense_5/kernel/Initializer/stateless_random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.


In [8]:
np.random.seed(np.random.randint(0,100))
zayev.run_batch()
# zayev.run_multiprocesses(num_worker=4)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-10-16 09:32:42.536906: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_17/bias/Assign' id:1814 op device:{requested: '', assigned: ''} def:{{{node dense_17/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_17/bias, dense_17/bias/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.s

episode: 1/20, score: -4510, average: -4510.00 
episode: 2/20, score: -4450, average: -4480.00 
episode: 3/20, score: -4390, average: -4450.00 
episode: 4/20, score: -4530, average: -4470.00 
episode: 5/20, score: -5030, average: -4582.00 
episode: 6/20, score: -4870, average: -4630.00 
episode: 7/20, score: -4250, average: -4575.71 
episode: 8/20, score: -3610, average: -4455.00 
episode: 9/20, score: -5310, average: -4550.00 
episode: 10/20, score: -4430, average: -4538.00 
episode: 11/20, score: -4130, average: -4500.91 
episode: 12/20, score: -4290, average: -4483.33 
episode: 13/20, score: -4490, average: -4483.85 
episode: 14/20, score: -5030, average: -4522.86 
episode: 15/20, score: -4750, average: -4538.00 
episode: 16/20, score: -3970, average: -4502.50 
episode: 17/20, score: -4110, average: -4479.41 
episode: 18/20, score: -4170, average: -4462.22 
episode: 19/20, score: -3910, average: -4433.16 
episode: 20/20, score: -4990, average: -4461.00 


In [4]:
# print(zayev.Actor.Actor)
# [-1.         -0.99999756  0.9822062  -1.         -0.99031776]
# zayev.load()
zayev.test()
print(zayev.env.the_current_time_step - relativedelta(hours=500, minutes=00))


stepping_a [ 1000.  1000. -1000.  1000. -1000. -1000.]
[[0.00000000e+00 5.00118726e+06 1.05052535e+03 4.97030050e+02
  5.00118726e+06 5.21645862e+02 5.00118726e+06 5.00000280e+06
  0.00000000e+00 5.00000280e+06 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.00228885e+06 4.08582721e+03 2.18418355e+03
  5.00228885e+06 2.18795080e+03 5.00228885e+06 5.00000100e+06
  0.00000000e+00 5.00000100e+06 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.00004795e+06 3.15027605e+03 1.62828197e+03
  5.00004795e+06 1.42512147e+03 5.00004795e+06 5.00000833e+06
  0.00000000e+00 5.00000833e+06 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.00004169e+06 2.45173832e+03 1.27288671e+03
  5.00004169e+06 1.14009002e+03 5.00004169e+06 5.00000150e+06
  0.00000000e+00 5.00000150e+06 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.00205018e+06 4.40424589e+03 2.07178664e+03
  5.00

In [ ]:
print(zayev.previous_state)
print(zayev.previous_actn)
print(zayev.latest_state)

In [ ]:
ztt = zayev.latest_state
stt_stt = zayev.latest_state[0][0]
print(stt_stt)

total_potfolio = zayev.latest_state[2][0]
for st_dta in stt_stt:
    total_potfolio = total_potfolio + st_dta[1]*st_dta[8]
print(total_potfolio)
print(zayev.env.the_current_time_step - relativedelta(hours=100))

In [8]:
tm = starting_time_step + relativedelta(hours=25)
print(tm)

1995-01-02 11:00:00


In [ ]:
zayev.latest_state

In [8]:
actp = np.array([1,2,3])*1000
print(actp)

[1000 2000 3000]


In [13]:
log_std = .5 * np.ones(5, dtype=np.float32)
std = np.exp(log_std)

print(log_std)
print(std)

[0.5 0.5 0.5 0.5 0.5]
[1.6487212 1.6487212 1.6487212 1.6487212 1.6487212]


In [6]:
# print(zayev.env.the_current_time_step)

1995-01-16 20:00:00+00:00


In [3]:
zayev.env.sample()

array([-0.10856622, -0.2379676 ,  0.86392075, -0.06428463, -0.27278227,
       -0.31639934], dtype=float32)

In [35]:
from gymnasium import spaces

wallet = 1
no_of_actions = 5 + wallet

# actns = [list(range(-1000,1001,1)) for i in range(no_of_stocks)]
# num_possible_values = 2001  # 2001 values from -1000 to 1000 (inclusive)
# actn_shape = gym.spaces.MultiDiscrete(np.array([[1001, 2],[1001, 2],[1001, 2],[1001, 2],[1001, 2]]))
# amount_shape = gym.spaces.MultiDiscrete([1001,1001,1001,1001,1001])



lower_bounds = [-1] * no_of_actions
upper_bounds = [1] * no_of_actions
actn_shape = spaces.Box(low=np.array(lower_bounds), high=np.array(upper_bounds))

def sample():
    action = actn_shape.sample()
    neg_mask = action < 0
    neg_sum = np.sum(action[neg_mask])

    pos_mask = action > 0
    pos_values_sum = np.sum(action[pos_mask])

    ratio_a = abs(-1 - neg_sum) / abs(neg_sum)
    ratio_b = 1 - ratio_a


    # Adjust negative values if their sum is less than -1
    if neg_sum < -1:
        action[neg_mask] *= ratio_b


    if pos_values_sum > 0:
        ratio_c = abs(max(-1.0, neg_sum)) / pos_values_sum
        action[pos_mask] *= ratio_c

    return action

print(sample())
print(np.sum(sample()))


[ 0.38293535  0.4029196  -0.3753671  -0.32930404  0.21414496 -0.29532892]
-7.450581e-09


In [11]:
actn_shape.sample()

array([ 0.43194687,  0.30413803, -0.99352896,  0.49561593, -0.4449103 ,
        0.7052002 ], dtype=float32)