In [1]:
import sys
import django
import os
file_dir = "/Users/mirbilal/Desktop/MobCommission/commissionV2/"
if file_dir not in sys.path:
    sys.path.insert(0, file_dir)

os.environ["DJANGO_SETTINGS_MODULE"] = "commissionerv2.settings"
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
django.setup()
from datetime import datetime
from os import environ
from services.zayev.service_layer.agent import PPOAgent as ZPPO
from matplotlib.dates import relativedelta
import numpy as np


2023-10-16 18:44:24.084719: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<Figure size 1800x900 with 0 Axes>

In [2]:

starting_time_step = datetime(year=1995, month=1, day=1, hour=10)

db_params = {
            'database': environ.get("POSTGRES_DB"),
            'user': environ.get("POSTGRES_USER"),
            'password': environ.get("POSTGRES_PASSWORD"),
            'host': environ.get("DB_HOST"),
            'port': environ.get("DB_PORT"),
        }
env_config = {
    "db_params": db_params, 
    "max_episode_steps": 5, 
    "the_current_time_step": starting_time_step,
    "print_output": False,
    "test_steps": 10,
    "n_step_stocks": 5,
    "n_step_cmmdties": 5
} 



zayev = ZPPO(env_config)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/optimizers/legacy/adam.py:118: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [3]:
print(zayev.Actor.Actor.summary())

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 stock_observation_input (I  [(None, 5, 14)]              0         []                            
 nputLayer)                                                                                       
                                                                                                  
 commodity_observation_inpu  [(None, 6, 7)]               0         []                            
 t (InputLayer)                                                                                   
                                                                                                  
 wallet_observation_input (  [(None, 1)]                  0         []                            
 InputLayer)                                                                                  

In [6]:
zayev.save()

2023-10-14 11:47:08.686920: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_7/kernel/Assign' id:1195 op device:{requested: '', assigned: ''} def:{{{node dense_7/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_7/kernel, dense_7/kernel/Initializer/random_normal)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.


In [3]:
np.random.seed(np.random.randint(0,100))
zayev.run_batch()
# zayev.run_multiprocesses(num_worker=4)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-10-16 18:44:40.408280: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-10-16 18:44:40.429091: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_4/bias/Assign' id:275 op device:{requested: '', assigned: ''} def:{{{node dense_4/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_4/bias, dense_4/bias/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
/Users/mirbilal/D

episode: 1/20, score: 40981503.733426295, average: 40981503.73 SAVING
episode: 2/20, score: 35165278.19398402, average: 38073390.96 
episode: 3/20, score: 32091582.963484876, average: 36079454.96 
episode: 4/20, score: 36511285.27606188, average: 36187412.54 
episode: 5/20, score: 28720915.122996848, average: 34694113.06 
episode: 6/20, score: 36587698.16577046, average: 35009710.58 
episode: 7/20, score: 29588215.996484365, average: 34235211.35 
episode: 8/20, score: 33686680.681458145, average: 34166645.02 
episode: 9/20, score: 27641919.623126805, average: 33441675.53 
episode: 10/20, score: 32555358.13989742, average: 33353043.79 
episode: 11/20, score: 30450652.758226864, average: 33089190.06 
episode: 12/20, score: 33543225.75678093, average: 33127026.37 
episode: 13/20, score: 31672367.758881744, average: 33015129.55 
episode: 14/20, score: 34401040.64762846, average: 33114123.20 
episode: 15/20, score: 32283585.515296664, average: 33058754.02 
episode: 16/20, score: 28249440.40

In [7]:
# print(zayev.Actor.Actor)
# [-1.         -0.99999756  0.9822062  -1.         -0.99031776]
# zayev.load()
zayev.test()

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-10-14 11:47:11.699993: W tensorflow/c/c_api.cc:305] Operation '{name:'lambda_1/SelectV2_1' id:1312 op device:{requested: '', assigned: ''} def:{{{node lambda_1/SelectV2_1}} = SelectV2[T=DT_FLOAT, _has_manual_control_dependencies=true](lambda_1/Greater, lambda_1/mul_1, lambda_1/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.



stepping_a [0. 0. 0. 0. 0. 0.]
[[0.00000000e+00 1.54208151e+02 1.56000000e+02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.20024527e+00 3.25000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.12407267e+02 4.15000000e+02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.07289884e+03 8.00000000e+03 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.77586463e+04 2.75000000e+04 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.61959633e+03 3.65000000e+03 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]]
[[   0.           86.68822578 1750.87558874  802.25604172   86.68913453
   849.91507752   86.69170479   86.8         230.41474654   86.8
     0.            0.            0.            0.        ]
 [   0.           24.88954193 5246.00036379 2418.23735942   24.89345208
  2569.22263713   24.90109842   25.    

In [4]:
print(zayev.previous_state)
print(zayev.previous_actn)
print(zayev.latest_state)

[array([[[ 0.00000000e+00,  9.11213600e+01,  1.86375560e+03,
          8.43394026e+02,  9.11286682e+01,  8.12241325e+02,
          9.11367558e+01,  9.07060374e+01,  6.16924999e+02,
          4.57877649e-03,  3.42364896e-03,  1.78727107e-02,
          2.18206005e-02,  2.36229798e-03],
        [ 0.00000000e+00,  2.41779196e+01,  5.54464133e+03,
          2.57827842e+03,  2.41807848e+01,  2.56736779e+03,
          2.41899120e+01,  2.42811314e+01,  1.05113037e+03,
         -4.25069882e-03,  1.46499537e-03, -5.63807603e-03,
         -4.70044073e-03, -4.14215075e-03],
        [ 0.00000000e+00,  1.23782552e+02,  1.08535259e+03,
          5.71966054e+02,  1.23803369e+02,  5.85407610e+02,
          1.23904789e+02,  1.28969082e+02,  1.00000000e+00,
         -4.02152953e-02, -4.85170838e-02, -4.65279353e-02,
         -3.08220810e-02, -5.28420393e-03],
        [ 0.00000000e+00,  4.11417867e+01,  6.18360859e+02,
          2.95563606e+02,  4.11519762e+01,  2.86372684e+02,
          4.11772975e+01,  

In [35]:
ztt = zayev.latest_state
stt_stt = zayev.latest_state[0][0]
print(stt_stt)

total_potfolio = zayev.latest_state[2][0]
for st_dta in stt_stt:
    total_potfolio = total_potfolio + st_dta[0]*st_dta[7]
print(total_potfolio)
print(zayev.env.the_current_time_step - relativedelta(hours=100))

[[8.19678646e+01 2.43880864e+03 9.75345014e+02 8.22008843e+01
  7.66613268e+02 8.23515861e+01 7.68176859e+01 6.51296015e+02]
 [2.62161971e+01 5.64381844e+03 2.32921692e+03 2.62239934e+01
  2.42789306e+03 2.62451703e+01 2.66008026e+01 1.00000000e+00]
 [1.70331760e+02 1.14572909e+03 5.41098317e+02 1.70358625e+02
  5.98110364e+02 1.70411557e+02 1.74174741e+02 1.65967199e+02]
 [6.12547799e+01 6.54401212e+02 2.76779553e+02 6.12573036e+01
  3.42052660e+02 6.12590837e+01 6.11700756e+01 1.00000000e+00]
 [2.21214677e+01 2.15738819e+03 9.18469113e+02 2.21449470e+01
  9.28346293e+02 2.22346375e+01 2.13678578e+01 9.37500000e+02]]
[102481.17548137]
1994-12-30 08:00:00+00:00


In [8]:
tm = starting_time_step + relativedelta(hours=25)
print(tm)

1995-01-02 11:00:00


In [6]:
zayev.latest_state

[array([[[  86.98892013, 1780.88718796,  806.78320262,   86.99418474,
           815.32319724,   87.01223627,   86.22798652,  231.66143027],
         [  24.55947431, 5311.76025676, 2294.7676268 ,   24.5622656 ,
          2544.55969405,   24.56600397,   24.61056939,  795.63826776],
         [ 139.2253307 , 1086.44600003,  505.13989644,  139.25715658,
           561.13738873,  139.33339698,  144.20254547,  126.31578947],
         [  38.81905216,  614.39851888,  328.47856092,   38.82553138,
           308.16662239,   38.84516044,   38.48886214,  533.33333333],
         [  21.18280565, 1786.27803173,  976.56194102,   21.18713267,
           841.46566394,   21.19766482,   21.08023049,  937.5       ]]]),
 array([[[1.71481016e+02],
         [3.49922248e+00],
         [4.32156117e+02],
         [7.54711667e+03],
         [2.72181363e+04],
         [3.93169616e+03]]]),
 array([[0]])]

In [8]:
actp = np.array([1,2,3])*1000
print(actp)

[1000 2000 3000]


In [13]:
log_std = .5 * np.ones(5, dtype=np.float32)
std = np.exp(log_std)

print(log_std)
print(std)

[0.5 0.5 0.5 0.5 0.5]
[1.6487212 1.6487212 1.6487212 1.6487212 1.6487212]


In [6]:
# print(zayev.env.the_current_time_step)

1995-01-16 20:00:00+00:00
