In [1]:
import sys
import django
import os
file_dir = "/Users/mirbilal/Desktop/MobCommission/commissionV2/"
if file_dir not in sys.path:
    sys.path.insert(0, file_dir)

os.environ["DJANGO_SETTINGS_MODULE"] = "commissionerv2.settings"
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
django.setup()
from datetime import datetime
from os import environ
from services.zayev.service_layer.agent import PPOAgent as ZPPO


2023-10-11 17:01:04.275890: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<Figure size 1800x900 with 0 Axes>

In [2]:

starting_time_step = datetime(year=1995, month=1, day=1, hour=10)



zayev = ZPPO(starting_time_step)

In [7]:
print(zayev.Actor.Actor.summary())

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 stock_observation_input (I  [(None, 5, 8)]               0         []                            
 nputLayer)                                                                                       
                                                                                                  
 commodity_observation_inpu  [(None, 6, 1)]               0         []                            
 t (InputLayer)                                                                                   
                                                                                                  
 wallet_observation_input (  [(None, 1)]                  0         []                            
 InputLayer)                                                                                

In [3]:
# print(zayev.Actor.Actor)
zayev.test()

2023-10-11 14:58:24.115153: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-10-11 14:58:24.141761: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_7/bias/Assign' id:261 op device:{requested: '', assigned: ''} def:{{{node dense_7/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_7/bias, dense_7/bias/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-10-11 14:58:

[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  1. -1.  1.]
[ 1.  1.  

In [3]:
zayev.run_batch()

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-10-11 16:31:38.712565: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-10-11 16:31:38.735618: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_7/kernel/Assign' id:256 op device:{requested: '', assigned: ''} def:{{{node dense_7/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_7/kernel, dense_7/kernel/Initializer/stateless_random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new

AttributeError: 'list' object has no attribute 'shape'

In [42]:
import numpy as np
import copy

# Your original list with corrected formatting
original_list = [
    np.array([[[6.18533117e+06, 1.27167986e+03, 3.27242924e+02, 6.18533118e+06, 2.25929212e+02, 6.18533121e+06, 6.12344432e+06, 6.95512187e+00],
              [5.14902154e+06, 1.73213343e+03, 4.09901119e+02, 5.14902154e+06, 6.54760917e+02, 5.14902154e+06, 5.14822946e+06, 4.23177655e+00],
              [5.22310567e+06, 2.27002018e+03, 6.42464946e+02, 5.22310567e+06, 4.29871624e+02, 5.22310567e+06, 5.21969722e+06, 1.30825354e+01],
              [5.03184443e+06, 6.91959690e+02, 2.03325204e+02, 5.03184443e+06, 1.38764497e+02, 5.03184443e+06, 5.03158268e+06, 1.00000000e+00],
              [5.88737714e+06, 6.07730985e+03, 1.54629231e+03, 5.88737714e+06, 1.60129385e+03, 5.88737715e+06, 5.85476184e+06, 1.00000000e+00]]]),
    np.array([[[2.11824527e+02],
              [3.90397460e+00],
              [4.83594046e+02],
              [9.62521579e+03],
              [2.22831137e+04],
              [3.27575791e+03]]]),
    np.array([[0]])
]

# Use np.vstack to stack the arrays
# stacked_array = np.array(original_list)
list2 = copy.deepcopy(original_list)
# for an in original_list:
#     print(an)
#     print("")
nw_lis = [original_list, list2]
# np.vstack(nw_lis)
# processed_data = []

# for element in nw_lis:
#     # Assuming each element contains three arrays
#     array1 = element[0]
#     array2 = element[1]
#     array3 = element[2]
#     print(array1, array2)
#     new_el = np.concatenate([element[0], element[1], element[2]], axis=1)
#     processed_data.append(new_el)

#     # Optionally, pad or preprocess the arrays if needed
#     # ...

# # input_data = [np.array(batch) for batch in processed_data]
# print(processed_data)
stks = np.vstack([nw_lis[0][0], nw_lis[1][0]])
cmmdts = np.vstack([nw_lis[0][1], nw_lis[1][1]])
wllts = np.vstack([nw_lis[0][2], nw_lis[1][2]])
print(wllts)
zayev.Actor.predict([stks, cmmdts, wllts])

[[0]
 [0]]


array([[ 1.,  1.,  1., -1.,  1.],
       [ 1.,  1.,  1., -1.,  1.]], dtype=float32)

In [ ]:
import numpy as np

# Your original list with corrected formatting
original_list = [
    np.array([[[6.18533117e+06, 1.27167986e+03, 3.27242924e+02, 6.18533118e+06, 2.25929212e+02, 6.18533121e+06, 6.12344432e+06, 6.95512187e+00],
              [5.14902154e+06, 1.73213343e+03, 4.09901119e+02, 5.14902154e+06, 6.54760917e+02, 5.14902154e+06, 5.14822946e+06, 4.23177655e+00],
              [5.22310567e+06, 2.27002018e+03, 6.42464946e+02, 5.22310567e+06, 4.29871624e+02, 5.22310567e+06, 5.21969722e+06, 1.30825354e+01],
              [5.03184443e+06, 6.91959690e+02, 2.03325204e+02, 5.03184443e+06, 1.38764497e+02, 5.03184443e+06, 5.03158268e+06, 1.00000000e+00],
              [5.88737714e+06, 6.07730985e+03, 1.54629231e+03, 5.88737714e+06, 1.60129385e+03, 5.88737715e+06, 5.85476184e+06, 1.00000000e+00]]]),
    np.array([[[2.11824527e+02],
              [3.90397460e+00],
              [4.83594046e+02],
              [9.62521579e+03],
              [2.22831137e+04],
              [3.27575791e+03]]]),
    np.array([[0]])
]


ar1 = np.array([[1,2],[2,3]])
ar2 = np.array([[1,2]])
nw = np.vstack([ar1, ar2])
print(ar1)
print(ar2)
print(nw)
abd = (1,2,3)
print(abd[0])