In [1]:
import sys
import django
import os
file_dir = "/Users/mirbilal/Desktop/MobCommission/commissionV2/"
if file_dir not in sys.path:
    sys.path.insert(0, file_dir)

os.environ["DJANGO_SETTINGS_MODULE"] = "commissionerv2.settings"
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
django.setup()
from datetime import datetime
from os import environ
from services.zayev.service_layer.agent import PPOAgent as ZPPO
from matplotlib.dates import relativedelta
import numpy as np


2023-11-08 15:41:32.776588: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<Figure size 1800x900 with 0 Axes>

In [16]:

starting_time_step = datetime(year=1995, month=1, day=1, hour=10)

db_params = {
    'database': environ.get("POSTGRES_DB"),
    'user': environ.get("POSTGRES_USER"),
    'password': environ.get("POSTGRES_PASSWORD"),
    'host': environ.get("DB_HOST"),
    'port': environ.get("DB_PORT"),
}
env_config = {
    "db_params": db_params, 
    "max_episode_steps": 15, 
    "the_current_time_step": starting_time_step,
    "print_output": False,
    "is_test": True,
    "test_steps": 15,
    "n_step_stocks": 5,
    "n_step_cmmdties": 5
} 



zayev = ZPPO(env_config)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/optimizers/legacy/adam.py:118: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [3]:
print(zayev.Actor.Actor.summary())

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 stock_observation_input (I  [(None, 5, 5)]               0         []                            
 nputLayer)                                                                                       
                                                                                                  
 commodity_observation_inpu  [(None, 6, 5)]               0         []                            
 t (InputLayer)                                                                                   
                                                                                                  
 volume_observation_input (  [(None, 5, 5)]               0         []                            
 InputLayer)                                                                                  

In [17]:
zayev.load()

2023-11-08 15:53:22.886590: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_22/bias/Assign' id:2093 op device:{requested: '', assigned: ''} def:{{{node dense_22/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_22/bias, dense_22/bias/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.


In [3]:
np.random.seed(np.random.randint(0,100))
zayev.run_batch()
# zayev.run_multiprocesses(num_worker=4)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-11-08 15:41:44.117502: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-11-08 15:41:44.137048: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_5/kernel/Assign' id:286 op device:{requested: '', assigned: ''} def:{{{node dense_5/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_5/kernel, dense_5/kernel/Initializer/stateless_random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new

episode: 1/20, score: 721176.7918225979, average: 721176.79 SAVING
episode: 2/20, score: -393105.4680843521, average: 164035.66 
episode: 3/20, score: 11018964.473237999, average: 3782345.27 SAVING
episode: 4/20, score: 7145298.020334386, average: 4623083.45 SAVING
episode: 5/20, score: -1427675.9428093615, average: 3412931.57 
episode: 6/20, score: 5364037.837053823, average: 3738115.95 
episode: 7/20, score: 10297253.225440178, average: 4675135.56 SAVING
episode: 8/20, score: 7909872.163712298, average: 5079477.64 SAVING
episode: 9/20, score: 4070090.8794852216, average: 4967323.55 
episode: 10/20, score: 11572562.114538472, average: 5627847.41 SAVING
episode: 11/20, score: 4205083.631797855, average: 5498505.25 
episode: 12/20, score: 4483297.549389762, average: 5413904.61 
episode: 13/20, score: 7738586.986094435, average: 5592726.33 
episode: 14/20, score: 13016139.336792115, average: 6122970.11 SAVING
episode: 15/20, score: 2806905.1004117075, average: 5901899.11 
episode: 16/20,

In [18]:
# print(zayev.Actor.Actor)
# [-1.         -0.99999756  0.9822062  -1.         -0.99031776]
# zayev.load()
zayev.test()

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-11-08 15:53:28.340093: W tensorflow/c/c_api.cc:305] Operation '{name:'lambda_3/SelectV2_1' id:1984 op device:{requested: '', assigned: ''} def:{{{node lambda_3/SelectV2_1}} = SelectV2[T=DT_FLOAT, _has_manual_control_dependencies=true](lambda_3/Greater, lambda_3/mul_1, lambda_3/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.


In [19]:
print(zayev.previous_state)
print(zayev.previous_actn)
print((zayev.env.the_current_time_step.replace(tzinfo=None) - datetime(year=1995, month=1, day=1, hour=10)).total_seconds()/3600)
print(zayev.latest_state)

[array([[[117.99938716, 115.20615779, 113.16964672, 110.92813348,
         109.90632851],
        [ 33.54095535,  34.27958618,  34.70920412,  35.10077482,
          35.47284248],
        [182.62717099, 188.43607898, 193.96532318, 200.48179416,
         206.98568882],
        [ 52.89142444,  54.70438447,  54.44258624,  54.84985467,
          55.72916342],
        [ 27.6522372 ,  27.25821393,  26.96255195,  26.88685228,
          27.21011622]]]), array([[[3.00701462e+02, 3.01888280e+02, 2.94465392e+02, 2.88884152e+02,
         2.85055873e+02],
        [2.77931941e+00, 2.80679331e+00, 2.84323437e+00, 2.84691868e+00,
         2.82123110e+00],
        [5.27056519e+02, 5.30180170e+02, 5.23190016e+02, 5.19538456e+02,
         5.13511903e+02],
        [1.09168575e+04, 1.10664050e+04, 1.10117018e+04, 1.10023625e+04,
         1.10626162e+04],
        [3.53073562e+04, 3.48219958e+04, 3.44134968e+04, 3.41151088e+04,
         3.38285843e+04],
        [4.44153013e+03, 4.39425359e+03, 4.31734053e+03,

In [20]:
ztt = zayev.latest_state
zt_env = zayev.env

total_potfolio = zayev.env.wallet_state
for ind in range(5):
    data_index = ind+1
    total_potfolio = total_potfolio + zt_env.stock_data[data_index]["price_snapshot"]*zt_env.shares_data[data_index]
print(total_potfolio)
print(zayev.env.the_current_time_step - relativedelta(hours=100))

280448.6373180951
1995-01-07 16:00:00+00:00


In [8]:
tm = starting_time_step + relativedelta(hours=25)
print(tm)

1995-01-02 11:00:00


In [6]:
zayev.latest_state

[array([[[  86.98892013, 1780.88718796,  806.78320262,   86.99418474,
           815.32319724,   87.01223627,   86.22798652,  231.66143027],
         [  24.55947431, 5311.76025676, 2294.7676268 ,   24.5622656 ,
          2544.55969405,   24.56600397,   24.61056939,  795.63826776],
         [ 139.2253307 , 1086.44600003,  505.13989644,  139.25715658,
           561.13738873,  139.33339698,  144.20254547,  126.31578947],
         [  38.81905216,  614.39851888,  328.47856092,   38.82553138,
           308.16662239,   38.84516044,   38.48886214,  533.33333333],
         [  21.18280565, 1786.27803173,  976.56194102,   21.18713267,
           841.46566394,   21.19766482,   21.08023049,  937.5       ]]]),
 array([[[1.71481016e+02],
         [3.49922248e+00],
         [4.32156117e+02],
         [7.54711667e+03],
         [2.72181363e+04],
         [3.93169616e+03]]]),
 array([[0]])]

In [8]:
actp = np.array([1,2,3])*1000
print(actp)

[1000 2000 3000]


In [13]:
log_std = .5 * np.ones(5, dtype=np.float32)
std = np.exp(log_std)

print(log_std)
print(std)

[0.5 0.5 0.5 0.5 0.5]
[1.6487212 1.6487212 1.6487212 1.6487212 1.6487212]


In [6]:
# print(zayev.env.the_current_time_step)

1995-01-16 20:00:00+00:00
