In [1]:
import sys
import django
import os
file_dir = "/Users/mirbilal/Desktop/MobCommission/commissionV2/"
if file_dir not in sys.path:
    sys.path.insert(0, file_dir)

os.environ["DJANGO_SETTINGS_MODULE"] = "commissionerv2.settings"
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
django.setup()
from datetime import datetime
from os import environ
from services.zayev.service_layer.agent import PPOAgent as ZPPO
from matplotlib.dates import relativedelta
import numpy as np


2023-10-12 19:14:49.399762: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<Figure size 1800x900 with 0 Axes>

In [2]:

starting_time_step = datetime(year=1995, month=1, day=1, hour=10)

db_params = {
            'database': environ.get("POSTGRES_DB"),
            'user': environ.get("POSTGRES_USER"),
            'password': environ.get("POSTGRES_PASSWORD"),
            'host': environ.get("DB_HOST"),
            'port': environ.get("DB_PORT"),
        }
env_config = {
    "db_params": db_params, 
    "max_episode_steps": 300, 
    "the_current_time_step": starting_time_step,
    "print_output": False,
    "test_steps": 100
} 



zayev = ZPPO(env_config)

/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/optimizers/legacy/adam.py:118: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [ ]:
print(zayev.Actor.Actor.summary())

In [10]:
zayev.save()

2023-10-12 11:49:11.501124: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_24/kernel/Assign' id:3721 op device:{requested: '', assigned: ''} def:{{{node dense_24/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_24/kernel, dense_24/kernel/Initializer/random_normal)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.


In [7]:
# np.random.seed(np.random.randint(0,10))
zayev.run_batch()
# zayev.run_multiprocesses(num_worker=4)

episode: 1/20, score: 48854.69264156878, average: 45777.64 
episode: 2/20, score: 95918.10379711664, average: 47451.60 
episode: 3/20, score: 11803.928871801603, average: 46371.65 
episode: 4/20, score: 130796.00268517956, average: 48569.19 
episode: 5/20, score: 48364.56818875371, average: 47056.55 
episode: 6/20, score: 76014.0689788439, average: 47933.80 
episode: 7/20, score: 32191.80136547936, average: 47898.58 
episode: 8/20, score: 42186.22666491673, average: 49248.56 
episode: 9/20, score: 79591.96927500726, average: 50499.77 
episode: 10/20, score: 75468.00244705513, average: 51207.55 
episode: 11/20, score: 56927.66802015784, average: 51190.37 
episode: 12/20, score: 23607.381008248005, average: 50994.45 
episode: 13/20, score: 35048.363044771264, average: 49744.81 
episode: 14/20, score: 146070.78104450268, average: 51511.67 
episode: 15/20, score: 55456.202695765984, average: 52457.28 
episode: 16/20, score: 46427.822962565886, average: 52217.46 
episode: 17/20, score: 6825

In [24]:
# print(zayev.Actor.Actor)
# [-1.         -0.99999756  0.9822062  -1.         -0.99031776]
# zayev.load()
zayev.test()

2023-10-12 19:13:28.201244: W tensorflow/c/c_api.cc:305] Operation '{name:'dense_26/kernel/Assign' id:2421 op device:{requested: '', assigned: ''} def:{{{node dense_26/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_26/kernel, dense_26/kernel/Initializer/stateless_random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2023-10-12 19:13:28.434187: W tensorflow/c/c_api.cc:305] Operation '{name:'lambda_4/SelectV2_1' id:2512 op device:{req

In [22]:
print(zayev.previous_state)
print(zayev.previous_actn)
print(zayev.latest_state)

[array([[[1.52699057e+02, 1.59610876e+04, 7.36979777e+02, 1.52704517e+02,
         5.81693347e+02, 1.52710224e+02, 1.52087833e+02, 6.46309628e+02],
        [2.51995869e+01, 8.72888042e+03, 2.40792423e+03, 2.52044428e+01,
         3.38610089e+03, 2.52131157e+01, 2.50898042e+01, 8.00000000e+02],
        [1.50760981e+02, 1.85230963e+03, 6.55517373e+02, 1.50779321e+02,
         4.89346921e+02, 1.50842878e+02, 1.54086095e+02, 1.00000000e+00],
        [3.50326955e+01, 1.08547914e+03, 2.49368059e+02, 3.50335886e+01,
         2.29734750e+02, 3.50365985e+01, 3.50805766e+01, 1.00000000e+00],
        [1.87200546e+01, 3.90986299e+03, 7.89353704e+02, 1.87211317e+01,
         7.27672188e+02, 1.87316410e+01, 1.87927922e+01, 9.37500000e+02]]]), array([[[1.39815383e+02],
        [4.72562807e+00],
        [4.42226204e+02],
        [7.56656221e+03],
        [2.23556928e+04],
        [3.59424991e+03]]]), array([[0]])]
[ 0.33333334  0.33333334 -0.3333333  -0.3333333   0.33333334 -0.3333333 ]
[array([[[1.52

In [25]:
ztt = zayev.latest_state
stt_stt = zayev.latest_state[0][0]
print(stt_stt)

total_potfolio = zayev.latest_state[2][0]
for st_dta in stt_stt:
    total_potfolio = total_potfolio + st_dta[0]*st_dta[7]
print(total_potfolio)

[[1.52419001e+02 1.60005291e+04 7.57802916e+02 1.52421865e+02
  6.04087155e+02 1.52424047e+02 1.52699057e+02 6.46309628e+02]
 [2.51821853e+01 8.81783100e+03 2.39878448e+03 2.51832983e+01
  3.27808268e+03 2.51849120e+01 2.51995869e+01 8.00000000e+02]
 [1.47940674e+02 1.87949453e+03 6.62104761e+02 1.47963755e+02
  4.81112867e+02 1.47996282e+02 1.50760981e+02 1.00000000e+00]
 [3.46065458e+01 1.11111750e+03 2.55223370e+02 3.46145133e+01
  2.26905869e+02 3.46510265e+01 3.50326955e+01 1.00000000e+00]
 [1.86370910e+01 3.92799701e+03 8.05119374e+02 1.86422028e+01
  7.33562640e+02 1.86510274e+01 1.87200546e+01 9.37500000e+02]]
[136310.43597307]


In [8]:
tm = starting_time_step + relativedelta(hours=25)
print(tm)

1995-01-02 11:00:00


In [6]:
zayev.latest_state

[array([[[  86.98892013, 1780.88718796,  806.78320262,   86.99418474,
           815.32319724,   87.01223627,   86.22798652,  231.66143027],
         [  24.55947431, 5311.76025676, 2294.7676268 ,   24.5622656 ,
          2544.55969405,   24.56600397,   24.61056939,  795.63826776],
         [ 139.2253307 , 1086.44600003,  505.13989644,  139.25715658,
           561.13738873,  139.33339698,  144.20254547,  126.31578947],
         [  38.81905216,  614.39851888,  328.47856092,   38.82553138,
           308.16662239,   38.84516044,   38.48886214,  533.33333333],
         [  21.18280565, 1786.27803173,  976.56194102,   21.18713267,
           841.46566394,   21.19766482,   21.08023049,  937.5       ]]]),
 array([[[1.71481016e+02],
         [3.49922248e+00],
         [4.32156117e+02],
         [7.54711667e+03],
         [2.72181363e+04],
         [3.93169616e+03]]]),
 array([[0]])]

In [8]:
actp = np.array([1,2,3])*1000
print(actp)

[1000 2000 3000]


In [13]:
log_std = .5 * np.ones(5, dtype=np.float32)
std = np.exp(log_std)

print(log_std)
print(std)

[0.5 0.5 0.5 0.5 0.5]
[1.6487212 1.6487212 1.6487212 1.6487212 1.6487212]


In [6]:
# print(zayev.env.the_current_time_step)

1995-01-16 20:00:00+00:00
